# Generated by Django 2.2.6 on 2019-11-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191106_1018'),
        ('authentication', '0002_auto_20191106_1148'),
    ]

    operations = [
    ]
