# Generated by Django 2.2.6 on 2019-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191104_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='created_by',
        ),
    ]
